//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupportSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SupportSystemPraksaEntities : DbContext
    {
        public SupportSystemPraksaEntities()
            : base("name=SupportSystemPraksaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<SupportSystemCategory> SupportSystemCategory { get; set; }
        public virtual DbSet<SupportSystemComments> SupportSystemComments { get; set; }
        public virtual DbSet<SupportSystemMain> SupportSystemMain { get; set; }
        public virtual DbSet<SupportSystemPriority> SupportSystemPriority { get; set; }
        public virtual DbSet<SupportSystemSection> SupportSystemSection { get; set; }
        public virtual DbSet<SupportSystemSeverity> SupportSystemSeverity { get; set; }
        public virtual DbSet<SupportSystemStatuses> SupportSystemStatuses { get; set; }
    }
}
