//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupportSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupportSystemMain
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SupportSystemMain()
        {
            this.SupportSystemComments1 = new HashSet<SupportSystemComments>();
        }
    
        public System.Guid Id { get; set; }
        public string Number { get; set; }
        public string Title { get; set; }
        public Nullable<System.Guid> IdStatus { get; set; }
        public Nullable<System.Guid> IdKategorija { get; set; }
        public Nullable<System.Guid> IdSeverity { get; set; }
        public Nullable<System.Guid> IdUser { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> DueOn { get; set; }
        public Nullable<System.DateTime> ResolvedOn { get; set; }
        public Nullable<System.Guid> IdPriority { get; set; }
        public string Steps { get; set; }
        public string Notes { get; set; }
        public Nullable<System.Guid> IdSystemSection { get; set; }
        public Nullable<System.DateTime> AcceptedOn { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual SupportSystemCategory SupportSystemCategory { get; set; }
        public virtual SupportSystemPriority SupportSystemPriority { get; set; }
        public virtual SupportSystemSection SupportSystemSection { get; set; }
        public virtual SupportSystemSeverity SupportSystemSeverity { get; set; }
        public virtual SupportSystemStatuses SupportSystemStatuses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupportSystemComments> SupportSystemComments1 { get; set; }
        public virtual SupportSystemSection SupportSystemSection1 { get; set; }
    }
}
