//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupportSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupportSystemComments
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> IdUser { get; set; }
        public Nullable<System.DateTime> OnDate { get; set; }
        public string Comment { get; set; }
        public string IdReply { get; set; }
        public Nullable<System.Guid> IdMain { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual SupportSystemMain SupportSystemMain1 { get; set; }
    }
}
